export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 4000,
  },
  {
    name: "Apr",
    "Active User": 2780,
  },
  {
    name: "May",
    "Active User": 3500,
  },
  {
    name: "June",
    "Active User": 2780,
  },
  {
    name: "July",
    "Active User": 1890,
  },
  {
    name: "Aug",
    "Active User": 2390,
  },
  {
    name: "sep",
    "Active User": 5000,
  },
  {
    name: "Oct",
    "Active User": 3490,
  },
  {
    name: "Nov",
    "Active User": 2000,
  },
  {
    name: "Dec",
    "Active User": 6000,
  },
];
export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 4000,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Kamrul Islam",
    avatar: "/assets/images/profile.jpg",
    email: "jhon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];

export const productRows = [
  {
    id: 1,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 3,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 4,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 5,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 6,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    productName: "Apple Airpods",
    img: "/assets/images/product_1.jpg",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
];
